export const dynamic = "force-static";
export const runtime = "edge";
import { ReactNode } from "react";
import type { Metadata } from "next";
import AdminHeader from "@/components/layouts/backend/AdminHeader";
import AdminFooter from "@/components/layouts/backend/AdminFooter";
import { ThemeProvider } from "@/components/theme-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminRootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AdminHeader />

          <div className="backend-wrapper">{children}</div>
          <AdminFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
